import os

DEBUG = False
DEV = os.getenv('FLASK_ENV') == 'development'
REDIS_URL = 'redis://127.0.0.1:6379' if not DEV else 'redis://'
SECRET_KEY = 'X2M89ALp1majWQAaa09b'
SEARCH_FILTER_HINTS_LIMIT = 20
SEARCH_FILTER_HINTS_THRESHOLD = 50
SEARCH_FILTER_HINTS_MAX_DIFFERENCE = 20
FILTER_SELECT_COLUMNS = ['geometry']
SEARCH_AREA_TABLE_NAME = 'search_area'
INTERSECTION_BUFFER = 1000
SIMPLIFY_RATE = 100
RESULTS_TABLE_PATH = 'app.parcel_results'
FILTERS_TABLE_PATH = 'app.filters'
PARCELS_TABLE_PATH = 'parcels.parcels'